server:
  port: 8080

spring:
  datasource:
    url: PLACE_HOLDER
    username: PLACE_HOLDER
    password: PLACE_HOLDER
    name: PLACE_HOLDER
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: PLACE_HOLDER
